---
# APPLY_FIXES: all
# VALIDATE_ALL_CODEBASE: true
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - REPOSITORY_GITLEAKS
  - SPELL_MISSPELL
  - SPELL_PROSELINT
  - JAVASCRIPT_ES
FILTER_REGEX_EXCLUDE: (\.envrc|\.git/*|node_modules/*|dist/*)
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (pnpm-lock\.yaml)
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: (.*\.sops\..*)
YAML_PRETTIER_CONFIG_FILE: .prettierrc.yaml
JSON_PRETTIER_CONFIG_FILE: .prettierrc.yaml
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
JAVASCRIPT_ES_ARGUMENTS: "{src,apps,libs,test}/**/*.ts"
JAVASCRIPT_ES_FILE_EXTENSIONS: ".ts"
