[env]
NODE_ENV = "development"

[tools]
# https://direnv.net/
direnv = "2.36.0"
# https://gitleaks.io/
gitleaks = "8.27.2"
# https://nodejs.org/
node = "22.16.0"
# https://pre-commit.com/
pre-commit = "4.2.0"
# https://taskfile.dev/
task = "3.38.0"
# https://pnpmp.io
pnpm = "10.12.1"
