[env]
NODE_ENV = "development"

[tools]
# https://direnv.net/
direnv = "2.37.1"
# https://gitleaks.io/
gitleaks = "8.28.0"
# https://nodejs.org/
node = "22.20.0"
# https://pre-commit.com/
pre-commit = "4.3.0"
# https://taskfile.dev/
task = "3.38.0"
# https://pnpmp.io
pnpm = "10.18.1"
