[env]
NODE_ENV = "development"

[tools]
# https://direnv.net/
direnv = "2.35.0"
# https://gitleaks.io/
gitleaks = "8.21.2"
# https://nodejs.org/
node = "22.12.0"
# https://pre-commit.com/
pre-commit = "4.0.1"
# https://taskfile.dev/
task = "3.38.0"
# https://pnpmp.io
pnpm = "9.15.4"
