---
name: MegaLinter

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/javascript@c217fe8f7bc9207062a084e989bd97efd56e7b9a # v8.0.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_STATUS_REPORTER only works if VALIDATE_ALL_CODEBASE is false!
          GITHUB_STATUS_REPORTER: true
          REPORTERS_MARKDOWN_TYPE: simple
          SHOW_ELAPSED_TIME: false
          SHOW_SKIPPED_LINTERS: true
